### ISSUE TITLE
xubuntu with i3wm - dmenu list with options is shown but non is executed

### ISSUE THREAD

**Issue by fogine** [jamcnaughton/hud-menu#3]
#### Environment:

Xubuntu 14.04
Python 3.4.3
i3wm (i3 version 4.12.31)
#### Environment Setup:

I use xfce4 environment for which I disabled `xfwm4`, `xfdesktop` and replaced them with `i3`
#### Issue:

For applications eg.: google-chrome, thunar, gimp, available menu entries are shown via dmenu. But no one is executed upon selection.

When I debug the `i3-hud-menu.py` script, it falls back to line [try_gtk_interface](https://github.com/jamcnaughton/i3-hud-menu/blob/master/i3-hud-menu.py#L181)

Neither error or warning is thrown.

I would be more then willing to debug the issue further, however I would need help with what I should look for, please.

**Comment by jmaris** [comment]
can also confirm this issue

**Comment by rodrigoscc** [comment]
Figured out the issue. Two lines solved the problem. The option selected was returned with a carret return at the end, removing it solved the problem.
Made a [fork](https://github.com/rstcruzo/i3-hud-menu).

**Comment by jamcnaughton** [comment]
Thanks. I've committed your changes into this repo as well.
