### ISSUE TITLE
[Feature] Feed synapse launcher

### ISSUE THREAD

**Issue by lf-araujo** [jamcnaughton/hud-menu#4]
Thanks for your brilliant script, it is extremelly useful. However, it would be a complete killer if it would integrate into synapse. Is this possible? The guys out on synapse resist to put their project into github, but I suspect it would be relatively easy to add it as a plugin.

**Comment by jamcnaughton** [comment]
Thanks for the idea. I think we want to wait till this work has matured further till its integrated with anything else - maybe when we've got the rest of the issues closed we can revisit this.
