### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rodrigoscc** [jamcnaughton/hud-menu#5]
When I run i3-hud-menu.py I get this error
```
Window id is : 0x1400007
Traceback (most recent call last):
  File "./i3-hud-menu.py", line 168, in <module>
    try_gtk_interface(gtk_bus_name_cmd, gtk_object_path_cmd)
  File "./i3-hud-menu.py", line 81, in try_gtk_interface
    gtk_bus_name = gtk_bus_name_cmd.split(' ')[2].split('\n')[0].split('"')[1]
IndexError: list index out of range
```

Service is running in the background and .profile is set according to documentation.

**Comment by jamcnaughton** [comment]
Hi, is this when selecting the last option in the list by any chance?

If not, does this happen with every application?

**Comment by jamcnaughton** [comment]
Error likely to be caused by lack of handling of a specific error output for non-gtk windows. A recent change should have fixed this.
