### ISSUE TITLE
Rofi is good, but different too.

### ISSUE THREAD

**Issue by rafaeln** [jamcnaughton/hud-menu#6]
Hi. I use dmenu with a nice font for many things in my i3 setup, so when you guys changed into rofi, it made it the hud stand out. I just reverted back to dmenu locally, but I would also like to suggest that maybe making it into an option could interest other people too.

Thanks for sharing this great piece of software!

**Comment by jamcnaughton** [comment]
Added the option to supply a command line argument to switch to dmenu. README updated to reflect this.
